spring:
  profiles:
    active: prod
    include: swagger
  jackson:
    serialization.indent_output: true
  data:
    elasticsearch:
      cluster-nodes: 192.168.0.6:9300
      clusterName: elasticsearch
    mongodb:
      uri: mongodb://192.168.0.6:27017
      database: new_pangolin_management_db

server:
  port: 8763
