spring:
  profiles:
    active: prod
    include: swagger
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false # we use gulp + BrowserSync for livereload
  jackson:
    serialization.indent_output: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  redis:
    database: 0
    host: 10.10.1.22
    port: 6379
  boot:
    admin:
      client:
        url: http://10.10.1.22:8762
eureka:
  instance:
    hostname: gateway-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: "*"
