spring:
    profiles:
        active: test
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
    redis:
      database: 0
      host: 192.168.3.2
      port: 46379
    boot:
      admin:
        client:
          url: http://localhost:8762
eureka:
  instance:
    hostname: gateway-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://localhost:8761/eureka/

server:
    port: 9000
management:
  endpoints:
    web:
      exposure:
        include: "*"
