spring:
  profiles:
    active: prod
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false # we use gulp + BrowserSync for livereload
  jackson:
    serialization.indent_output: true
  data:
    elasticsearch:
      cluster-nodes: 10.10.1.22:9300
      clusterName: elasticsearch
  rabbitmq:
    username: faxin
    password: faxin
    host: 10.10.1.22
    virtual-host: faxin
    port: 5672
  redis:
    database: 0
    host: 10.10.1.22
    port: 6379
  boot:
    admin:
      client:
        url: http://localhost:8762
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    hostname: repair-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9005
